name: 'Composite Action test'
description: 'Test composite action steps'
inputs:
  greeted:
    description: 'Who to greet'
    required: true
    default: 'world'
  substeps:
    description: 'Steps to run'
    required: true
    default: []
runs:
  using: "composite"
  steps:
    - name: greeting
      run: |
        echo Hello ${{ inputs.greeted }}
      shell: bash
    - name: script
      run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Run echo args
      run: echo_args.sh ${{ inputs.substeps }}
    - name: goodbye
      run: goodbye.sh
      shell: bash
